# Config for https://github.com/apps/release-drafter
template: |
  ## TODO: Added/Removed/Fixed/Changed

  $CHANGES

  ## Upgrading

  To upgrade, update your `pipeline.yml` files:

  ```diff
  steps:
    - plugins:
  -    harshadbhatia/aws-environment#v0.1.2:
  +    harshadbhatia/aws-environment#v0.1.3:
         debug: true # Default False
         secret_name: mysecretname # Default "buildkite/{queue_name}/ssh-private-key"
  ```
