#!/bin/bash

set -uo pipefail


HOOKS_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)


main() {

    export PATH="$PATH:$HOOKS_DIR/../bin"

     if [[ -n $AWS_ACCOUNT_ID && -n $AWS_ACCOUNT_ID ]]; then
        export AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        export CDK_DEFAULT_ACCOUNT=${AWS_ACCOUNT_ID}
        export CDK_DEFAULT_REGION=${AWS_DEFAULT_REGION}

        echo "Exported AWS_ACCOUNT_ID:${AWS_ACCOUNT_ID}"
        echo "AWS_DEFAULT_REGION:${AWS_DEFAULT_REGION}"
        echo "CDK_DEFAULT_ACCOUNT:${AWS_ACCOUNT_ID}"
        echo "CDK_DEFAULT_REGION:${AWS_DEFAULT_REGION}"
     else
        echo "Error in setting AWS_ACCOUNT_ID"
     fi
    
}

main
